language: elixir
elixir:
  - 1.6.6
  - 1.7.4
  - 1.9.4
otp_release:
  - 18.3
  - 19.3
  - 20.0
  - 21.0
  - 22.0
jobs:
  exclude:
    - elixir: 1.6.6
      otp_release: 22.0
    - elixir: 1.7.4
      otp_release: 18.3
    - elixir: 1.9.4
      otp_release: 18.3
    - elixir: 1.9.4
      otp_release: 19.3

after_success:
  - mix coveralls.travis
